[WIP]TE-6915 using new facade method to check table existance
spryker/event-behavior pull request #61
Opened 2020-11-10 12:28 UTC by gechetspr

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2020-11-11 09:28 UTC, bezpiatovs approved these changes

2020-11-12 13:21 UTC, stereomon approved these changes

2020-11-30 16:11 UTC, dereuromark commented
Can you rebase this on top of master, so that GitHubActions is used?
And we can see those results then in Release App for validation (green)?

2020-12-22 15:55 UTC, asmarovydlo requested changes
Instead of `Adjusted TriggerManager in order to use new table existence check instead of try catch block.` in changelogs please mention the facade method that impacted.

2020-12-22 15:55 UTC, asmarovydlo commented on src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
> +        } catch ( \Throwable $exception) {
We shouldn't silently ignore exceptions, especially if we no longer expect any (We do the check for table/query existence beforehand).
Please leave only `ConnectionException` here.

2020-12-22 15:55 UTC, asmarovydlo commented on src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
> -        } catch (PropelException | ConnectionException | EventBehaviorQueryNotExistsException $e) {
`EventBehaviorQueryNotExistsException` no longer used, and can be deprecated.
1. `Throw` annotation in the query container should be deprecated. 
2. Functionality that throws an exception in query container should be moved to protected method and deprecated.
3. The exception class should be deprecated.

2020-12-22 15:55 UTC, asmarovydlo commented on src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
> +    protected const TABLE_NAME_EVENT_BEHAVIOR_ENTITY_CHANGE = 'spy_event_behavior_entity_change';
Please add `@uses` link to \Orm\Zed\EventBehavior\Persistence\Map\SpyEventBehaviorEntityChangeTableMap::TABLE_NAME

2020-12-23 17:24 UTC, asmarovydlo requested changes
Deprecations should be mentioned in the changelogs.

2020-12-23 17:24 UTC, asmarovydlo commented on src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
> +    protected function checkRequiredClasses():void
```suggestion
    protected function checkRequiredClasses(): void
```

2020-12-23 17:24 UTC, asmarovydlo commented on src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
> +     * @throws EventBehaviorQueryNotExistsException
```suggestion
     * @throws EventBehaviorQueryNotExistsException
     * 
     * @return void

```

2020-12-24 19:30 UTC, asmarovydlo approved these changes

2020-12-28 13:47 UTC, gechetspr reviewed
Small change required.

Also I can't approve this PR as long as I want the one who created it
@asmarovydlo

2020-12-28 13:47 UTC, gechetspr commented on src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
> +     * @throws EventBehaviorQueryNotExistsException
Please use FQCN in docblocks

2020-12-30 14:00 UTC, asmarovydlo approved these changes

2021-01-13 12:57 UTC, gechetspr commented on src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
> +    protected function checkRequiredClasses(): void
This is very generic name for the query container. I would prefer smth like `eventBehaviorEntityClassExists`

2021-01-14 09:07 UTC, gechetspr reviewed
Can't approve because I was created PR, but all good from my side

2021-01-21 11:23 UTC, dereuromark commented on composer.json
> +    "spryker/propel": "^3.28.0",
For tests we need to use "dev-... as" here for them to run
Did you do that before? So we know all is good when releasing?

I wonder if we need to fix up the auto release process to include these aliasing changes for release.
So we have better testing beforehand.

2021-02-09 15:00 UTC, merged